
language: minimal

os:
    - linux

sudo: false

# The apt packages below are needed for sphinx builds. A full list of
# packages that can be included can be found here:
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz

stages:
   - name: Build tests
   - name: Tests with various Astropy/Numpy versions
   - name: Test docs, PEP8, and coverage
   - name: Remote data tests (allowed to fail)

stage: Build tests

# setting up environment variables and the build matrix
env:
    global:
        # default environment variables
        - PYTHON_VERSION=3.7
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - EVENT_TYPE='pull_request push'
        - PIP_DEPENDENCIES='scipy matplotlib ads synphot https://github.com/astropy/astroquery/archive/master.zip pytest-astropy codecov'
        - ADS_DEV_KEY=TjUyPHFOH48m5Katkeq0UCZQcejTg6bDbTuTGHxT

    matrix:
        - PYTHON_VERSION=3.5 SETUP_CMD='egg_info'
        - PYTHON_VERSION=3.7 SETUP_CMD='egg_info'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:

        # Try other Astropy/Numpy versions.
        - os: linux
          stage: Tests with various Astropy/Numpy versions
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.12 ASTROPY_VERSION=2 PYTEST_VERSION='<3.7'

        - os: osx
          stage: Tests with various Astropy/Numpy versions
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.13 ASTROPY_VERSION=3 PYTEST_VERSION='<3.7'

        - os: linux
          stage: Tests with various Astropy/Numpy versions
          env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.14 ASTROPY_VERSION=3 PYTEST_VERSION='<3.7'

        # Test docs, PEP8, and coverage
        - os: linux
          stage: Test docs, PEP8, and coverage
          env: MAIN_CMD='test --coverage' SETUP_CMD=''

        - os: linux
          stage: Test docs, PEP8, and coverage
          env: SETUP_CMD='build_docs -w' PIP_DEPENDENCIES="`echo $PIP_DEPENDENCIES sphinx-astropy`"

        - os: linux
          stage: Test docs, PEP8, and coverage
          env: MAIN_CMD='pycodestyle sbpy --count' SETUP_CMD=''

        # Remote data tests
        - os: linux
          stage: Remote data tests (allowed to fail)
          env: DEBUG=True SETUP_CMD='test -R -V -a "--durations=50"' PYTEST_VERSION='<3.7'

    allow_failures:
        - os: linux
          stage: Remote data tests (allowed to fail)
          env: DEBUG=True SETUP_CMD='test -R -V -a "--durations=50"' PYTEST_VERSION='<3.7'


install:
   - git clone git://github.com/astropy/ci-helpers.git
   - source ci-helpers/travis/setup_conda.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then
          codecov;
      fi